config/routes.rb
SampleApp::Application.routes.draw do

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/browse', :to => 'pages#browse'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
match "/auth/:provider/callback" => "sessions#createauto"
match "/signout" => "sessions#destroy"
  match '/newlocation', :to => 'locations#new'
  match '/newcategory', :to => 'categories#new'
  
  get '/microposts/new', :to => 'microposts#new'
  resources :users,   :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post, :qualifications => :get}
  resources :locations
  resources :categories
  resources :tags, :memeber => {:roll => :get}, :has_many => [:users, :microposts]

  
  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=>[:create, :destroy, :show], :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post}
  resources :users do
    get 'tags', :on => :member
    get 'qualifications', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end
  
  resources :microposts do
    get 'tags', :on => :member
    get 'qualified', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end

  resources :tags do
    get 'roll', :on => :member
  end
  

   root :to => "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :bio, :location_id, :tags
  has_many :microposts, :dependent => :destroy
  validates :password, :presence => true, :confirmation => true, :length => {:within => 6..40}
  before_save :encrypt_password
  has_and_belongs_to_many :tags
  belongs_to :location
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :presence => true, :length => {:maximum => 50}
  validates :email, :presence => true, :format => {:with => email_regex}, :uniqueness => {:case_sensitive => false}

def self.create_with_omniauth(auth)
  create! do |user|
    user.password = "omniauth"
    if auth['provider'] == "facebook"
    user.email = auth['extra']['user_hash']["email"]
else
  user.email = auth['user_info']['email']      
    end
    user.name = auth["user_info"]["name"]
  end
end


  def has_tag?(tag)
    self.tags.include?(tag)
  end

  def has_tags
    Tag.find(:all, :order => "name") - not_have_tags
  end
  
  def not_have_tags
    Tag.find(:all, :order => "name") - self.tags
  end
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  
  def self.authenticate(email, submitted_password)
    user = User.find_by_email(email)
    return nil if user.nil?
    user if user.has_password?(submitted_password)
  end
  
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end
  
  def feed
    Micropost.where("user_id = ?", id)
  end
  
  
  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end
    
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
    
    
    
    
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:show, :new, :create]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user, :only => :destroy
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end

  
  def new
    @title = "sign up"
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @title = @user.name
    @microposts = @user.microposts.paginate(:page => params[:page])
    query = Micropost.order("created_at desc")
    @posts = []
    Micropost.all.each do |post|
      passed = true
      post.tags.each do |tag|
        passed = false unless @user.tags.include?(tag)
      end
      if passed
        @posts << post
      end
    end
    
  end

  def qualifications
    @user = User.find(params[:id])
    @title = "Qualifications"
    @posts = []
    Micropost.order("created_at desc").each do |post|
      passed = true
      post.tags.each do |tag|
        passed = false unless @user.tags.include?(tag)
      end
      if passed
        @posts << post
      end
    end
    
    @feed_items = @posts.paginate(:page => params[:page])    
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = 'You have succesfully signed up.'
      redirect_to @user
    else
      @title = "sign up"
      render 'new'  
      
    end
  end
  
  def edit
    @title = "Edit user"
    @user = User.find(params[:id])
    @tags = @user.tags
  end

  def update
    @tags = @user.tags
    if @user.update_attributes(params[:user])
      flash[:success] = "profile updated."
      redirect_to @user
    else
      @title = "edit user"
      render 'edit'
    end
  end
  
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "user destroyed"
    redirect_to users_path
  end
  
  def tags
    @user = User.find(params[:id])
    @tags = @user.tags
  end

  def tag_add
      @user = User.find(params[:id])

    unless params[:tag] == nil
      tags = Tag.all
     params[:tag].each do |tag|
      @tag = Tag.find(tag)
      @user.tags << @tag
    end
   
    flash[:notice] = 'Skills were successfully added.'
    else
      
      flash[:notice] = 'You didn\'t select a skill to add.'
    end
    redirect_back_or edit_user_path
  end
  
  def tag_remove
    
    @user = User.find(params[:id])
    unless params[:tag] == nil
    tags = Tag.all
    params[:tag].each do |tag|
      @tag = Tag.find(tag)
      @user.tags.delete(@tag)
    end
   
    flash[:notice] = 'Skills were successfully removed'
else
  flash[:notice] = 'You didn\'t select a skill to remove.'
end
    redirect_back_or edit_user_path
  end
  
  
  private
  
  
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end
    
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {:size =>50})
    gravatar_image_tag(user.email.downcase, :alt => user.name, :class => 'gravatar', :gravatar => options)
  end
end

app/views/users/_user.html.erb
<table class = "microposts" summary="Tag microposts">
<tr>
  <td class='gravatar'>
      <%= gravatar_for user, :size =>60, :default=>'identicon'%>
  </td>
  <td class="micropost">
    <%= link_to user.name, user%>
    <div id="tagsDiv">
      <%if user.tags.count > 0%>
        <% user.tags.each do |tag|%>
         <%=link_to tag.name , tag%>
      <%end%>
      <%else%>
      <%end%>
    </div>
  </td>
</tr>
</table>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'dashboard', :media => 'screen'%>

<h1>Settings</h1>
<div id="tabsBar">
  <div id="credsTab">
    <a>Credentials</a>
  </div>
  <div id="bioTab">
    <a>User Info</a>
  </div>
  <div id="skillsTab">
    <a>Skills</a>
  </div>
</div>



<div id="credsContent">
<%= form_for (@user) do |f|%>
<%=render 'shared/error_messages', :object => f.object%>
  
  <div class = "field">
    <%= f.label :display_name%><br/>
    <%= f.text_field :name, :disabled => true%>
  </div>
  <div class = "field">
    <%= f.label :email%> </br>
    <%= f.text_field :email%>
  </div>
  <div class = "field">
    <%=f.label :password%><br/>
    <%=f.password_field :password%>
  </div>
  <div class = "field">
    <%=f.label :password_confirmation, "Confirmation"%><br/>
    <%=f.password_field :password_confirmation%>
  </div>
  <div class ="actions">
    <%=f.submit "Save Profile"%>
  </div>

  
</div>
  
  
<div id="bioContent">
  <div id="locationBox" class = "field">
    <%= f.label :location_id%><br/>
    <%= f.select :location_id, ["Select a location"] + Location.find(:all, :order => "name").collect{|s| [s.name, s.id]}%>
  </div> 
  <div id="gravatarBox">
  <%= gravatar_for @user, :default =>'identicon'%><br/>
  <a href="http://gravatar.com/emails">Change display picture</a>
  </div>
  <div id="empty"></div> 
  <div id="bioBox" class = "actions">
    <%= f.label :bio%> <br/>
    <%= f.text_area :bio%>
  </div>
    <div class ="actions">
    <%=f.submit "Save Profile"%>
  </div>
  <%end%>  
</div>
  
  

  
<div id="skillsContent">
  
  
<div id="currentSkills">
<h1><%= @user.name%>'s skills</h1>
<%if @tags.length > 0%>
  <%= form_tag(tag_remove_user_path(@user)) do%>
  <%= select_tag(:tag, options_from_collection_for_select(@user.has_tags, :id, :name), :multiple => true)%>
  <br/>
  <%= submit_tag "Remove skills"%>
  <%end%>
  <%else%>
  <p>No skills listed.</p>
<%end%>
</div>


<div id="addSkills">
<h1>Add new skills</h1>
<% if @user.tags.count < Tag.count then%>
  <%= form_tag(tag_add_user_path(@user)) do%>
  <%= select_tag(:tag, options_from_collection_for_select(@user.not_have_tags, :id, :name), :multiple => true)%>
  <br/>
  <%= submit_tag 'Add skills'%>
<%end%>
<%else%>
<p> <%=h @user.name%> already has all the skills. </p>
<%end%>
</div>
</div>

<p><%=link_to "Back", user_path%></p>

app/views/users/index.html.erb
<h1>All users</h1>

<%=will_paginate @users%>
  <%= render @users%>
<%=will_paginate @users%>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div id="left">
<%= form_for (@user) do |f|%>
<%=render 'shared/error_messages', :object => f.object%>
  <div class = "field">
    <%= f.label :display_name%><br/>
    <%= f.text_field :name%>
  </div>
  <div class = "field">
    <%= f.label :email%> </br>
    <%= f.text_field :email%>
  </div>
  <div class = "field">
    <%=f.label :password%><br/>
    <%=f.password_field :password%>
  </div>
  <div class = "field">
    <%=f.label :password_confirmation, "Confirmation"%><br/>
    <%=f.password_field :password_confirmation%>
  </div>
  <div class ="actions">
    <%=f.submit "Sign up"%>
  </div>
  <%end%>
</div>

<script>
signUpLoad()
</script>

<%= set_focus_to_id 'user_name' %>
<div id="right">
  <h3>Or, have a Facebook account?</h3>
  <ul>
    <li id="clickMe">
      <a href="/auth/facebook">.</a>
    </li>
  </ul>
</div>

app/views/users/qualifications.html.erb
<%=link_to "<- Back to #{@user.name}", user_path%>
  <table class = "front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class = "micropost">Jobs recommended for <%=@user.name %></h1>
        <%=render 'shared/feed'%>
      </td>
     
      
    </tr>
    
    
    
    
    
    
  </table>

app/views/users/show.html.erb
<table class ="profile" summary = "profile information">
  <tr>
     <td class = "main">
      <h1>
        <%= gravatar_for @user, :default =>'identicon'%>
        <%=@user.name%>
      </h1>     
      <%unless @user.microposts.empty?%>
      <table class = "microposts" summary="User microposts">
        <%= render @microposts%>
      </table>
      <%= will_paginate @microposts%>
      <%end%>
      
      
      
      
    </td>
    
    
    
    <td class = "sidebar round">
      <strong>Display name:</strong> <%=@user.name%> <br/>
       <%unless @user.location.blank?%>
      <strong>Location: </strong> <%=@user.location.name%> <br/>
      <%else%>
      <strong>Location:</strong> Unknown
      <%end%>
      <br/>
      <strong>Posts:</strong> <%=@user.microposts.count%> <br/>
      <strong>Job recommendations: </strong> <%=link_to "#{@posts.count}", qualifications_user_path%> <br/>
      
      <%if @user.bio.blank?%>
      <strong>Bio: </strong> <%= @user.bio%> <br/>
      <%else%>
      <strong>Bio: </strong> <%= @user.bio.html_safe%> <br/>
      <%end%>
      <strong>Tags: </strong>
    <div id="tagsDiv">
      <%if @user.tags.count > 0%>
        <% @user.has_tags.each do |tag|%>
         <%=link_to tag.name , tag%>
       <%end%>
      <%else%>
      <%end%>
    </div>

    </td>
  
  
  
  </tr>
</table>




<h1>Leave <%=@user.name%> a comment:</h1>
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'fileajob'; // required: replace example with your forum shortname

    // The following are highly recommended additional parameters. Remove the slashes in front to use.
    // var disqus_identifier = 'unique_dynamic_id_1234';
    // var disqus_url = 'http://example.com/permalink-to-page.html';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments.</a></noscript>
  </div>

app/views/users/tags.html.erb
<h1><%= @user.name%>'s skills</h1>

<%if @tags.length > 0%>
  <% form_tag(tag_remove_user_path(@user)) do%>
  <table>
    <tr>
      <th>Skill</th>
      <th>Remove?</th>
    </tr>
    <% for tag in @tags do%>
    <tr>
      <td><%=h tag.name%></td>
      <td><%= check_box_tag "tags[]", tag.id%></td>
    </tr>
    <%end%>    
  </table>
  <br/>
  <%= submit_tag "Remove checked skills"%>
  <%end%>
  <%else%>
  <p>Does not have any tags.</p>
<%end%>

<h2>Add new skills</h2>
<% if @user.tags.count < Tag.count then%>
  <% form_tag(tag_add_user_path(@user)) do%>
  <%= select_tag(:tag, options_from_collection_for_select(@user.not_have_tags, :id, :name))%>
  <%= submit_tag 'Add'%>
<%end%>
<%else%>
<p> <%=h @user.name%> already has all the skills. </p>
<%end%>

<p><%=link_to "Back", edit_user_path%></p>