config/routes.rb
SampleApp::Application.routes.draw do

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/browse', :to => 'pages#browse'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
match "/auth/:provider/callback" => "sessions#createauto"
match "/signout" => "sessions#destroy"
  match '/newlocation', :to => 'locations#new'
  match '/newcategory', :to => 'categories#new'
  
  get '/microposts/new', :to => 'microposts#new'
  resources :users,   :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post, :qualifications => :get}
  resources :locations
  resources :categories
  resources :tags, :memeber => {:roll => :get}, :has_many => [:users, :microposts]

  
  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=>[:create, :destroy, :show], :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post}
  resources :users do
    get 'tags', :on => :member
    get 'qualifications', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end
  
  resources :microposts do
    get 'tags', :on => :member
    get 'qualified', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end

  resources :tags do
    get 'roll', :on => :member
  end
  

   root :to => "pages#home"

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :user_id, :location_id, :title, :category_id, :compensation
  belongs_to :user
  belongs_to :location
  belongs_to :category
  
  default_scope :order => 'microposts.created_at DESC'
  
  
  has_and_belongs_to_many :tags
  validates :title, :presence => true, :length => {:maximum => 100}
  validates_numericality_of :compensation, :on => :create
  validates :content, :presence => true, :length => {:minimum => 3, :maximum => 1000}
 # validates :user_id, :presence => true
 # validates :location_id, :presence => true

 def has_tag?(tag)
    self.tags.include?(tag)
  end
  

 def has_tags
    Tag.find(:all, :order => "name") - not_have_tags
  end
  
  def not_have_tags
    Tag.find(:all, :order => "name") - self.tags
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :authenticate, :only => [:create, :destroy]
  before_filter :authorized_user, :only => [:destroy, :edit, :update]

    
 # query = Micropost.order("created_at DESC")
 # query = query.where("location_id = ?", params[:location_id]) unless params[:location_id].blank?
 # query = query.where("category_id = ?", params[:category_id]) unless params[:category_id].blank?
 # @microposts = query.all
def tag_name
  tag.name if tag
end

def tag_name=(name)
  self.tag = Tag.find_or_create_by_name(name) unless name.blank?
end
  def edit
    @title = "Edit Post"
    @micropost = Micropost.find(params[:id])
    @tags = @micropost.tags
  end

  def update
    if @micropost.update_attributes(params[:micropost])
      flash[:success] = "post updated."
      redirect_to @micropost
    else
      @title = "edit micropost"
      render 'edit'
    end
  end

  
  def create
    @micropost = current_user.microposts.build(params[:micropost])
    logger.debug "The object is #{params[:micropost]}"
    if @micropost.save
      flash[:success] = 'Job successfully filed!'
      redirect_to :action => :tags, :id => @micropost

    else
      @title = "New Post"
      render 'new'
    end
  end
  
  def new
    @title = "new post"
    @micropost = Micropost.new
    @tags = @micropost.tags
  end
  
  def destroy
    @micropost.destroy
    redirect_back_or root_path
  end
  
  def show
    @micropost = Micropost.find(params[:id])
    @title = @micropost.title    
    
  end

  def qualified
    @micropost = Micropost.find(params[:id])
    @title = "Qualified candidates"
    @users = []
    User.all.each do |user|
      passed = true
      @micropost.tags.each do |tag|
        passed = false unless user.tags.include?(tag)
      end
      if passed
        @users << user
      end
    end
    
    @users= @users.paginate(:page => params[:page])    
  end

  def tags
    @micropost = Micropost.find(params[:id])
    @tags = @micropost.tags
  end


  def tag_add
    @micropost = Micropost.find(params[:id])
    tags = Tag.all
    params[:tag].each do |tag|
      @tag = Tag.find(tag)
      @micropost.tags << @tag
    end
   
    flash[:notice] = 'Tags were successfully added'

    redirect_to :action => :tags, :id => @micropost
  end
  
  def tag_remove
    @micropost = Micropost.find(params[:id])
    tags = Tag.all
    params[:tag].each do |tag|
      @tag = Tag.find(tag)
      @micropost.tags.delete(@tag)
    end
   
    flash[:notice] = 'Tags were successfully removed'

    redirect_to :action => :tags, :id => @micropost
  end


  
  private
    def authorized_user
      @micropost = Micropost.find(params[:id])
      redirect_to root_path unless current_user?(@micropost.user)
    end
end

app/views/microposts/_micropost.html.erb
<tr>
  
    <td class = "gravatar">
    <%= gravatar_for micropost.user, :default =>'identicon', :size => 50%>
  </td>
  <td class = "micropost">
    
    
    <span class ="title"><%= link_to micropost.title, micropost%></span><br/>

    <span class ="content"><%= micropost.content.html_safe[0..256] + "..."%></span>
    <div id="tagsDiv">
    
      <%if micropost.tags.count > 0%>
        <% micropost.tags.each do |tag|%>
         <%=link_to tag.name , tag%>
       <%end%>
      <%else%>
      <%end%>
    </div>
    <span class ="timestamp">
      <%= time_ago_in_words(micropost.created_at)%> ago <%= link_to micropost.user.name, micropost.user%>
    </span>

  </td>
  <% if current_user?(micropost.user)%>

  <%end%>
  
</tr>

app/views/microposts/edit.html.erb
<h1>Edit post</h1>
<%= form_for (@micropost) do |f|%>
<%=render 'shared/error_messages', :object => f.object%>
  <div class = "field">
    <%= f.label :title%><br/>
    <%= f.text_field :title%>
  </div>
  <div class = "field">
    <%= f.label :location_id%><br/>
    <%= f.select :location_id, Location.find(:all, :order => "name").collect{|s| [s.name, s.id]}%>
  </div>
  <div class = "field">
    <%= f.label :category_id%><br/>
    <%= f.select :category_id, Category.find(:all, :order => "name").collect{|s| [s.name, s.id]}%>
  </div>


  <div class = "field">
    <%= f.label :content%><br/>
    <%= f.text_area :content%>
  </div>
  <div class = "field">
    <%= f.label :compensation%><br/>
    <%= f.text_field :compensation%>
  </div>
    
    <%=link_to "Edit tags", tags_micropost_path%><br/>
    <div class ="actions">
      <%=f.submit "Done"%>
    </div>

  <%end%>

app/views/microposts/new.html.erb
<h1>Create a Post</h1>
<%= form_for (@micropost) do |f|%>
<%=render 'shared/error_messages', :object => f.object%>
  <div class = "field">
    <%= f.label :title%><br/>
    <%= f.text_field :title%>
  </div>
  <div class = "field">
    <%= f.label :location_id%><br/>
    <%= f.select :location_id, Location.find(:all, :order => "name").collect{|s| [s.name, s.id]}%>
  </div>
  <div class = "field">
    <%= f.label :category_id%><br/>
    <%= f.select :category_id, Category.find(:all, :order => "name").collect{|s| [s.name, s.id]}%>
  </div>


  <div class = "field">
    <%= f.label :content%><br/>
    <%= f.text_area :content, :cols =>30, :rows => 100%>
  </div>
  <div class = "field">
    <%= f.label :compensation%><br/>
    <%= f.text_field :compensation%>
  </div>
  <div class ="actions">
    <%=f.submit "Next"%>
  </div>

  <%end%>
    
<%= set_focus_to_id 'title' %>

app/views/microposts/qualified.html.erb
<%=link_to "<- Back", micropost_path%>
  <table class = "front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class = "micropost">Users qualified for <%=@micropost.title %></h1>
        <%unless @users.count == 0%>
        <%=will_paginate @users%>
  <%= render @users%>
<%=will_paginate @users%>
<%else%>
Sorry, no users currently have the skills needed for the job.
 <%end%> 
      </td>
     
      
    </tr>
    
    
    
    
    
    
  </table>

app/views/microposts/show.html.erb
<div id="wrapper" class ="micropost_profile" summary = "micropost information">
  <div id="titleHolder">
    <h1>
      <%=@micropost.title%>
    </h1>
    <div id="colorBar"></div>
    <table>
      <tr>
         <th>
        <div id="locationName">
          Location: <%=@micropost.location.name%> 
        </div>         
        </th>
        <th>

          <div id ="locationName">
            Category: <%=@micropost.category.name%>
           </div>           
        </th>

      </tr>
      
      
    </table>
         
  </div>
  
  <div id="description">
    <%=@micropost.content.html_safe%>
  </div>
  <div id="tags">
    
  </div>
  <div id="compensation">
    $<%=@micropost.compensation%> per hour
  </div>
  <div id="information">
  </div>
  <div id="tagsDiv">
    <strong>Tags:</strong>
    <%if @micropost.tags.count > 0%>
      <% @micropost.tags.each do |tag|%>
      <%=link_to tag.name , tag%>
    <%end%>
    <%else%>
      none.
    <%end%>
  </div>
  <table>
  <td>
    <% if current_user?(@micropost.user)%>
    <%= link_to "edit", edit_micropost_path%> | 
    <%= link_to "delete", @micropost, :method => :delete, :confirm => "you sure?", :title => @micropost.content%> |
    <%= link_to "qualified candidates", qualified_micropost_path%>
  <%end%>      
  </td>    
  </table>
<div id="userwrapper">
  <div id="userInfo">
  <div id="timeCheck"><%= time_ago_in_words(@micropost.created_at)%> ago</div>
  <div id="gravastuff">
  <%= gravatar_for @micropost.user, :size =>30, :default=>'identicon'%>
  <%= link_to @micropost.user.name, @micropost.user%>
  </div>
  </div>
</div>


  
<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'fileajob'; // required: replace example with your forum shortname

    // The following are highly recommended additional parameters. Remove the slashes in front to use.
    // var disqus_identifier = 'unique_dynamic_id_1234';
    // var disqus_url = 'http://example.com/permalink-to-page.html';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments.</a></noscript>
  </div>

app/views/microposts/tags.html.erb
<%= stylesheet_link_tag 'newPostTags', :media => 'screen'%>

<div id="currentSkills">
<h2><%= @micropost.title%>'s tags</h2>

<%if @tags.length > 0%>
  <%= form_tag(tag_remove_micropost_path(@micropost)) do%>
    <%= select_tag(:tag, options_from_collection_for_select(@micropost.has_tags, :id, :name), :multiple => true)%>
    
  <%= submit_tag "Remove tags"%>
  <%end%>
  <%else%>
  <p>Oops, this post has no tags, add some now.</p>
<%end%>
</div>


<div id="newSkills">
<h2>Add new skills</h2>
<% if @micropost.tags.count < Tag.count then%>
  <%= form_tag(tag_add_micropost_path(@micropost)) do%>

  <%= select_tag(:tag, options_from_collection_for_select(@micropost.not_have_tags, :id, :name), :multiple => true)%>
  <%= submit_tag 'Add tags'%>
<%end%>
<%else%>
<p> <%=h @micropost.title%> already has all the tags. </p>
<%end%>
</div>


<div id="links">
<p><%=link_to "Back", edit_micropost_path%> | <%=link_to "Done", qualified_micropost_path%></p>
</div>