config/routes.rb
SampleApp::Application.routes.draw do

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/browse', :to => 'pages#browse'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
match "/auth/:provider/callback" => "sessions#createauto"
match "/signout" => "sessions#destroy"
  match '/newlocation', :to => 'locations#new'
  match '/newcategory', :to => 'categories#new'
  
  get '/microposts/new', :to => 'microposts#new'
  resources :users,   :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post, :qualifications => :get}
  resources :locations
  resources :categories
  resources :tags, :memeber => {:roll => :get}, :has_many => [:users, :microposts]

  
  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=>[:create, :destroy, :show], :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post}
  resources :users do
    get 'tags', :on => :member
    get 'qualifications', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end
  
  resources :microposts do
    get 'tags', :on => :member
    get 'qualified', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end

  resources :tags do
    get 'roll', :on => :member
  end
  

   root :to => "pages#home"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :microposts, :dependent => :destroy
  attr_accessible :name, :category_id, :user_id
  validates :name, :presence => true, :length => {:maximum => 50}

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @title = "new category"
    @category = Category.new
  end

  def index
    @title = "all categories"
    @categories = Category.paginate(:page => params[:page])
  end

  def create
    @category = Category.new(params[:category])
    if @category.save
      flash[:success] = 'category created!'
      redirect_to @category
    else
      @title = "new category"
      render 'new'
    end
  end

  def show
    @category = Category.find(params[:id])
    @title = @category.name
    query = @category.microposts
    query = query.order("created_at DESC")
    query = query.where("location_id = ?", params[:location_id]) unless params[:location_id].blank?
    @microposts = query.all.paginate(:page => params[:page])

  end
end

app/views/categories/_category.html.erb
<tr>
  <td>
    <div id="holder">
    <%= link_to category.name, category%>
    <div id="numberCount">
      <%= category.microposts.count%>
    </div>
    </div>
  </td>
</tr>

app/views/categories/index.html.erb
<%= stylesheet_link_tag 'indexCustom', :media => 'screen'%>

<h1>All categories</h1>


<% if signed_in?%>
<% if current_user.admin?%>
  <%= link_to "Create new category", newcategory_path%>
<%end%>
<%end%>


<%=will_paginate @categories%>
<div id="holder">
<div id="numberExplain"># of posts</div>
</div>
<ul class ="categories">
  <table class = "microposts" summary="Tag microposts">
    <tbody>
  <%= render @categories%>
  </tbody>
  </table>
</ul>
<%=will_paginate @categories%>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= form_for (@category) do |f|%>
<%=render 'shared/error_messages', :object => f.object%>
  <div class = "field">
    <%= f.label :name%><br/>
    <%= f.text_field :name%>
  </div>
  <div class ="actions">
    <%=f.submit "Add"%>
  </div>
  <%end%>

<%= set_focus_to_id 'category_name' %>

app/views/categories/show.html.erb
<table class ="category_profile" summary = "category information">
  <tr>
     <td class = "main">
      <h1>
        <%=@category.name%>
      </h1>     
      
       <%unless @category.microposts.empty?%>
      <table class = "microposts" summary="category microposts">
        <%= render @microposts%>
      </table>
      <%= will_paginate @microposts%>
      <%end%>     
      
    </td>

  
  
  
  </tr>
</table>