config/routes.rb
SampleApp::Application.routes.draw do

  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  match '/browse', :to => 'pages#browse'
  match '/about', :to => 'pages#about'
  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
match "/auth/:provider/callback" => "sessions#createauto"
match "/signout" => "sessions#destroy"
  match '/newlocation', :to => 'locations#new'
  match '/newcategory', :to => 'categories#new'
  
  get '/microposts/new', :to => 'microposts#new'
  resources :users,   :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post, :qualifications => :get}
  resources :locations
  resources :categories
  resources :tags, :memeber => {:roll => :get}, :has_many => [:users, :microposts]

  
  resources :sessions, :only=> [:new, :create, :destroy]
  resources :microposts, :only=>[:create, :destroy, :show], :has_many => [:tags], :member => {:tags => :get, :tag_add => :post, :tag_remove => :post}
  resources :users do
    get 'tags', :on => :member
    get 'qualifications', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end
  
  resources :microposts do
    get 'tags', :on => :member
    get 'qualified', :on => :member
    member do
      post 'tag_add'
      post 'tag_remove'
    end
  end

  resources :tags do
    get 'roll', :on => :member
  end
  

   root :to => "pages#home"

end

app/views/layouts/_footer.html.erb
<footer>
  <div id="footerInner">
    <div id="footerBar">
    <div id="Posts">
      <p>Search Posts</p>
      <ul>
        <li><%= link_to "View By Tags", tags_path%></li>
        <li><%= link_to "View By Categories", categories_path%></li>
        <li><%= link_to "View By Locations", locations_path%></li>
      </ul>
    </div>
    <div id="Help">
      <p>Help Center</p>
      <ul>
        <li>Support</li>
        <li>Tour</li>
      </ul>
    </div>
    <div id="Company">
      <p>Company</p>
      <ul>
        <li><%=link_to "About", about_path%></li>
        <li><%=link_to "Contact", contact_path%></li>
        <li><%=link_to "Privacy Policy", about_path%></li></li>
        <li><%=link_to "Terms", about_path%></li>
      </ul>
    </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div id="headerBG">
    <header>
      <div id="headerInner">
      <div id="logoDiv">
        <%=link_to image_tag("logo.png", :alt =>"logo"), root_path %>
        

      </div>
      <% if signed_in?%>
        <div id="welcome">
          Good luck filing a job <%=link_to current_user.name, current_user%>!
          <h5>Not <%= current_user.name%>? Then <%=link_to "Sign out", signout_path, :method => :delete%></h5>
        </div>
        <%end%>
        <div id="facebookStuff">
          <script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
        <fb:like href="http://www.facebook.com/pages/FileAJob/121199847951972" layout="button_count" show_faces="false" width="450"></fb:like>
        </div>
      <div id="accountNav">
        <ul>
          <% if signed_in?%>
            <li><%=link_to "Profile", current_user%></li>
            <li><%=link_to "Settings", edit_user_path(current_user)%>  </li>
            <%end%>

          <li><%=link_to "Browse", browse_path%></li>
          <% if signed_in?%>
            <li><%=link_to "Create a Post", microposts_new_path%></li>
            <%else%>
          <li><%= link_to "Login", signin_path%></li> 
          <li><%= link_to "Sign up", signup_path%></li>
            <%end%>
        </ul>
      </div>
      </div>
      </div>

    </header>

app/views/layouts/_navBar.html.erb
<div id="navigationBar" class = "round">
        <ul>
          <li><%= link_to "Home", root_path%></li>
          <li><%= link_to "Locations", locations_path%></li>
          <li><%= link_to "Categories", categories_path%></li>
          <%if signed_in?%>
          <%if current_user.admin?%>
          <li><%=link_to "Users", users_path%></li>
          <%end%>
          <li><%=link_to "Profile", current_user%></li>
          <li><%=link_to "Settings", edit_user_path(current_user)%></li>
          <li><%=link_to "New Post", microposts_new_path%></li>
          <%end%>
          
          <li><%= link_to "Help", about_path%></li>
        </ul>
    </div>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'%>
  <%= stylesheet_link_tag 'blueprint/print', :media => 'print'%>
  <%= stylesheet_link_tag 'custom', :media => 'screen'%>
  <%= stylesheet_link_tag 'custom2', :media => 'screen'%>

  <%= javascript_include_tag 'jquery-1.4.4.min.js', 'jquery-ui-1.8.8.custom.min.js', 'autocomplete-rails.js', 'rails.js', 'wmd.js', 'markdown.js'  %>
  <%= stylesheet_link_tag 'jquery-ui-1.8.4.custom.css' %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%="File A Job"%></title>
  <link rel="shortcut icon" href="/images/logoForTab.png">
  <%= csrf_meta_tag %>
  <%=render 'layouts/stylesheets'%>
  <%=javascript_include_tag :defaults%>
  <%=javascript_include_tag 'jquery-1.4.4.min'%>

</head>
<body>
  <div class = "container">
    <%=render 'layouts/header'%>
    <div id="content">
      <div id="contentInner">
      <section class ="round">
      <% flash.each do |key, value|%>
      <div class = "flash <%=key%>"> <%= value%></div>
      <%end%>
      <%=yield%>
    </section>
    <div id="clearContent"></div>
    </div>
    </div>
    <%=render'layouts/footer'%>
    <%=debug(params) if Rails.env.development?%>
    
    
    
  </div>



</body>

<script>
load()
</script>
</html>